[package]
name = "tracker-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "active-tracker-agent"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracker-core = { path = "../tracker-core" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

